config/routes.rb
require 'resque/server'
Rails.application.routes.draw do

  root to: 'stocks#show'
  get 'stocks' => 'stocks#show'
  get 'stocks/show'
  get 'stocks/import'
  post 'stocks/import'
  get 'stocks/list'
  post 'stocks/list'
  get 'stocks/setup'
  post 'stocks/setup'
  get 'stocks/check'
  post 'stocks/check'
  get 'stocks/upload'
  post 'stocks/upload'
  get 'stocks/download'

  post 'stocks/delete'

  post 'stocks/regist'

  get 'home/show'


  mount Resque::Server.new, at: "/resque"

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    get '/sign_in' => 'devise/sessions#new'
  end
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => {
   :registrations => 'users/registrations'
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/stock.rb
class Stock < ApplicationRecord
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController

  require 'nokogiri'
  require 'open-uri'
  require 'uri'
  require 'csv'
  require 'peddler'
  require 'typhoeus'

  before_action :authenticate_user!, except: [:regist]
  protect_from_forgery :except => [:regist]

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end

  def regist
    if request.post? then
      user = params[:email]
      password = params[:password]
      limit = params[:limit]
      new_user = User.find_or_initialize_by(email: user)
      new_user.update(
        password: password,
        admin_flg: false
      )
      account = Account.find_or_create_by(user: user)
      account.update(sku_limit: limit.to_i)
    end
    redirect_to root_url
  end


  def show
    user = current_user.email
    @admin_flg = current_user.admin_flg
    @stock = Stock.where(email: user)
    @account = Account.find_or_create_by(user: user)
    if @account.sku_limit == nil then
      @account.update(sku_limit: 20000)
    end

    if @stock != nil then
      @total_sku = @stock.count
      if @stock.first != nil then
        @start_date = @stock.first.access_date
      else
        @start_date = "-"
      end

      if @stock.last != nil then
        @end_date = @stock.last.access_date
      else
        @end_date = "-"
      end

      if @account != nil then
        @upload_date = @account.upload_date
        @report_id = @account.report_id
      else
        @upload_date = "-"
        @report_id = "-"
      end
    else
      @total_sku = 0
      @start_date = "-"
      @end_date = "-"
      @upload_date = "-"
      @report_id = "-"
    end
  end

  def import
    flash[:normal]
    if request.post?
      logger.debug("\n\nStart Debug!!")
      data = params[:file]
      logger.debug("\n\n")
      tuser = current_user.email
      @account = Account.find_by(user: tuser)
      if @account.sku_limit == nil then
        @account.update(sku_limit: 20000)
      end
      maxsku = Account.find_by(user: tuser).sku_limit
      st = Stock.where(email: tuser).count

      if st > maxsku.to_i then
        flash[:alarm] = "SKUが上限数を超えています"
        redirect_to stocks_import_path
      else
        if data != nil then
          temp = File.open(data.path)
          body = temp.read
          new_body = body.gsub(/\R/, "\n")
          #csv = CSV.table(data.path)
          csv = CSV.parse(new_body)
          logger.debug(csv[0])
          #if csv.headers.include?(:sku) then
          if csv[0][0] == "sku" then
            logger.debug("sku header")
            #td = csv[:sku]
            td = csv
            SkuImportJob.perform_later(td, current_user.email)
            flash[:success] = "インポート成功"
          end
        end
      end
    end
  end

  def setup
    user = current_user.email
    @account = Account.find_or_create_by(user: user)
    if @account.sku_limit == nil then
      @account.update(sku_limit: 20000)
    end
    if request.post? then
      @account.update(user_params)
    end
  end

  def list
    flash[:normal]
    user = current_user.email
    @stock = Stock.where(email: user).limit(20000)
    if request.post?
      logger.debug("\n\nStart Debug!!")
      data = params[:file]
      logger.debug("\n\n")
      tuser = current_user.email

      if data != nil then
        csv = CSV.table(data.path)
        logger.debug("data is ok")
        logger.debug(csv.headers)
        if csv.headers.include?(:sku) then
          logger.debug("sku header")
          td = csv[:sku]
          for snum in td
            dstock = @stock.find_by(sku: snum)
            if dstock != nil then
              dstock.delete
            end
          end
          flash[:success] = "削除成功"
        elsif csv.headers.include?(:deleteall) then
          logger.debug("data is delete")
          skus = Stock.where(email: tuser)
          skus.delete_all
          flash[:success] = "全SKU削除成功"
        end
      end
    end
  end

  def download
    user = current_user.email
    @stock = Stock.where(email: user)
    d = Date.today
    str = d.strftime("%Y%m%d")
    respond_to do |format|
      format.csv do
        send_data render_to_string, filename: "sku_list_" + str + ".csv", type: :csv
      end
    end
  end

  def check
    logger.debug("監視開始")
    user = current_user.email
    @stock = Stock.where(email: user)
    AuctionCheckJob.perform_later(user)
    sleep(0.5)
    redirect_to stocks_show_path
  end

  def delete
    if request.post?
      tuser = current_user.email
      skus = Stock.where(email: tuser)
      skus.delete_all
      flash[:success] = "全SKU削除成功"
    end
    redirect_to stocks_setup_path
  end

  def upload
    logger.debug("\n\n")
    logger.debug("Upload Start")
    cuser = current_user.email
    FeedUploadJob.perform_later(cuser)
    redirect_to stocks_show_path
  end

  private
  def user_params
     params.require(:account).permit(:user, :seller_id, :aws_token, :relist_only, :sku_limit, :sku_header, :cw_room_id, :cw_api_token, :leadtime, :delete_sku)
  end

end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/stocks/export.html.erb
<div class="page-header" id="banner">
  <div class="row">
    <div class="col-lg-10 col-md-10">
      <h1>SKUリストの表示</h1>
      <div class="page-header"></div>
      <div class="table-responsive">
      <table class="table table-striped table-hover table-bordered">
        <thead class="thead-inverse">
          <tr>
            <th width="15%">SKU</th>
            <th width="40%">商品名</th>
            <th width="20%">更新日時</th>
            <th width="10%">在庫有無</th>
          </tr>
        </thead>
        <tbody>
          <% for temp in @stock %>
          <tr>
            <td><%= temp.sku %></td>
            <td><%= temp.title%></td>
            <td><%= temp.access_date %></td>
            <td><%= temp.validity %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    </div>
  </div>
</div>

app/views/stocks/import.html.erb
<div class="page-header" id="banner">
  <div class="row">
    <div class="col-lg-10 col-md-10">
      <h1>監視対象のインポート</h1>
      <p class="lead">SKUのリストをインポート</p>

      <%= form_tag({controller: "stocks", action: "import", method: "post"}, {multipart: true}) do %>
        <div class="form-group">
          <%= file_field_tag :file %>
        </div>
        <%= submit_tag "インポート", class: "form-control-button" %>
      <% end %>

      <% if flash[:alarm] %>
        <br>
        <br>
        <div class="alert alert-danger col-sm-3">
          <%= flash[:alarm] %>
        </div>
      <% end %>

      <% if flash[:success] %>
        <br>
        <br>
        <div class="alert alert-success col-sm-3">
          <%= flash[:success] %>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/stocks/list.html.erb
<style type="text/css">
table.table-headerfixed {
/*    width: 100%;*/
}

table.table-headerfixed thead,
table.table-headerfixed tbody,
table.table-headerfixed tr,
table.table-headerfixed td,
table.table-headerfixed th {
    display: block;
}

table.table-headerfixed tr:after {
    content: ' ';
    display: block;
    visibility: hidden;
    clear: both;
}

table.table-headerfixed tbody {
    height: 290px;
    overflow-y: scroll;
}

table.table-headerfixed thead {
    /* fallback */
    width: 97%;
    /* minus scroll bar width */
    width: calc(100% - 17px);
}

table.table-headerfixed tbody td,
table.table-headerfixed thead th {
    float: left;
    height: 60px;
}

.ellipsis {
    overflow: hidden;
    white-space: nowrap;
    text-overflow: ellipsis;
}

</style>

<script type="text/javascript">
function submitbtn() {
    // 「OK」ボタン押下時
    if (confirm('実行しますか？')) {
        alert('OK');
    }
    // 「キャンセル」ボタン押下時
    else {
        alert('キャンセル');
    }
}
</script>

<div class="page-header" id="banner">
  <div class="row">
    <div class="col-lg-10 col-md-10">
      <h1>SKUリストの表示</h1>

      <p class="lead">削除の場合はSKU記載ファイルをインポート</p>
      <%= form_tag({controller: "stocks", action: "list", method: "post"}, {multipart: true}) do %>
        <div class="form-inline">
          <div class="form-group" style="width: 350px">
            <%= file_field_tag :file %>
          </div>
          <%= submit_tag "インポート", class: "form-control-button" %>
        </div>
      <% end %>
      <br>
      <%= link_to "CSV出力", stocks_download_path(format: :csv), class: "btn btn-primary" %>
      <br>
      <br>
      <table class="table table-striped table-hover table-bordered table-headerfixed">
        <thead class="thead-inverse">
          <tr>
            <th width="15%">SKU</th>
            <th width="45%">商品名</th>
            <th width="20%">更新日時</th>
            <th width="10%">在庫有無</th>
            <th width="10%">期限切れ</th>
          </tr>
        </thead>
        <tbody>
          <% for temp in @stock %>
          <tr>
            <td width="15%"><%= temp.sku %></td>
            <td width="45%"><%= temp.title%></td>
            <td width="20%"><%= temp.access_date %></td>
            <td width="10%"><%= temp.validity %></td>
            <td width="10%"><%= temp.expired %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <% if flash[:alarm] %>
        <br>
        <br>
        <div class="alert alert-danger col-sm-3">
          <%= flash[:alarm] %>
        </div>
      <% end %>

      <% if flash[:success] %>
        <br>
        <br>
        <div class="alert alert-success col-sm-3">
          <%= flash[:success] %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/stocks/setup.html.erb
<div class="page-header" id="banner">
  <div class="row">
    <div class="col-lg-8">
      <h1>在庫管理機能の設定</h1>
      <%= form_for(@account, {url: stocks_setup_path, method: 'post'}) do |f| %>
        <p class="lead">MWSアカウントの設定</p>
        <div class="form-group">
          <%= f.label :seller_id, "セラーID" %>
          <%= f.text_field :seller_id, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :aws_token, "MWS認証トークン" %>
          <%= f.text_field :aws_token, class: 'form-control'  %>
        </div>
        <p class="lead">在庫チェック時の出品設定</p>
        <fieldset class="form-group">
        <div class="form-check">
          <label class="form-check-label">
            <%= f.radio_button 'relist_only', 'false', {class: 'form-check-input'}  %>
            再出品・取下げのどちらも有効
          </label>
        </div>
        <div class="form-check">
          <label class="form-check-label">
            <%= f.radio_button 'relist_only', 'true', {class: 'form-check-input'}  %>
            再出品のみ有効
          </label>
        </div>
        </fieldset>
        <p class="lead">オークションID期限切れ時の設定</p>
        <fieldset class="form-group">
        <div class="form-check">
          <label class="form-check-label">
            <%= f.radio_button 'delete_sku', 'true', {class: 'form-check-input'}  %>
            アマゾンからSKUごと削除
          </label>
        </div>
        <div class="form-check">
          <label class="form-check-label">
            <%= f.radio_button 'delete_sku', 'false', {class: 'form-check-input'}  %>
            出品取り下げのみ
          </label>
        </div>
        </fieldset>
        <p class="lead">在庫改定時の設定</p>
        <div class="form-group">
          <%= f.label :leadtime, "リードタイム ※在庫改定CSVに記載する発送までの日数、数字を記入" %>
          <%= f.text_field :leadtime, class: 'form-control'  %>
        </div>
        <br>
        <p class="lead">チャットワーク連携設定 <small>※在庫監視の経過状況をチャットワークで通知</small></p>
        <div class="form-group">
          <%= f.label :cw_api_token, "APIトークン" %>
          <%= f.text_field :cw_api_token, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :cw_room_id, "ルームID" %>
          <%= f.text_field :cw_room_id, class: 'form-control'  %>
        </div>
        <div class="actions">
          <%= f.submit "設定する", {id: "setup_btn", onClick: 'alert("更新しました")'} %>
        </div>
      <% end %>
      <br><br>
      <%= form_tag({controller: "stocks", action: "delete", method: "post"}) do %>
        <%= submit_tag "SKU全削除", class: "btn btn-danger" %>
      <% end %>
      <% if flash[:success] %>
        <br>
        <br>
        <div class="alert alert-success col-sm-3">
          <%= flash[:success] %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/stocks/show.html.erb
<div class="page-header" id="banner">
  <div class="row">
    <div class="col-lg-8 col-md-7">
      <h1>Stock Checker</h1>
      <p class="lead">アマゾン-ヤフオクの在庫管理システム</p>
      <div style="display:inline-flex">
      <%= form_tag(stocks_check_path) do %>
        <%= submit_tag "監視開始", {onClick: 'alert("監視を開始します")'} %>
      <% end %>
      &nbsp;&nbsp;&nbsp;&nbsp;
      <%= form_tag(stocks_upload_path) do %>
        <%= submit_tag "在庫改定", {onClick: 'alert("在庫改定を開始します")'} %>
      <% end %>
      </div>
      <div class="page-header"><h2>実行状況 <small> SKU登録上限数：<%= @account.sku_limit.to_i %>件</small></h2></div>
      <table class="table table-striped table-hover table-bordered">
        <thead class="thead-inverse">
          <tr>
            <th>監視対象件数</th>
            <th>監視開始日時</th>
            <th>監視終了日時</th>
            <th>在庫改定日時</th>
            <th>レポートID</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= @total_sku %></td>
            <td><%= @start_date %></td>
            <td><%= @end_date %></td>
            <td><%= @upload_date %></td>
            <td><%= @report_id %></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>